language: node_js
node_js:
  - lts/*
  - stable

cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: build
      node_js: lts/*
      script:
        - yarn build
      if: branch != master

    - stage: release
      node_js: lts/*
      script:
        - yarn build
      after_success:
        - yarn semantic-release
      if: branch = master
