language: node_js
node_js:
  - lts/*
  - stable

cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: build
      node_js: lts/*
      script:
        - yarn build
      branches:
        except:
          - master

    - stage: release
      node_js: lts/*
      script:
        - yarn test
        - yarn build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - yarn semantic-release
      branches:
        only:
          - master
